#!/usr/bin/env python3
"""Generate daily research report from saved data files."""
import json
import os
import urllib.request
from datetime import date
from xml.etree import ElementTree

today = str(date.today())
REPORT_DIR = "daily_reports"
api_key = os.environ.get("LLM_API_KEY", "")
os.makedirs(REPORT_DIR, exist_ok=True)

# --- Parse arXiv ---
papers = []
try:
    root = ElementTree.fromstring(open("/tmp/arxiv.xml", encoding="utf-8").read())
    ns = {"a": "http://www.w3.org/2005/Atom"}
    for entry in root.findall("a:entry", ns)[:6]:
        t = entry.find("a:title", ns)
        title = t.text.strip().replace("\n", " ") if t is not None else "No title"
        u = entry.find("a:id", ns)
        url = u.text.strip() if u is not None else ""
        a = []
        for author in entry.findall("a:author", ns):
            n = author.find("a:name", ns)
            if n is not None:
                a.append(n.text)
        papers.append({"title": title, "url": url, "authors": ", ".join(a[:3])})
except Exception as e:
    print(f"arXiv parse error: {e}")

# --- Parse GitHub ---
repos = []
try:
    gh = json.load(open("/tmp/gh.json"))
    for item in gh.get("items", [])[:5]:
        repos.append({
            "name": item.get("full_name", ""),
            "url": item.get("html_url", ""),
            "desc": (item.get("description") or "")[:120],
            "stars": item.get("stargazers_count", 0),
            "updated": (item.get("updated_at") or "")[:10],
        })
except Exception as e:
    print(f"GitHub parse error: {e}")

# --- Check npm ---
npm_ver = "?"
try:
    req = urllib.request.Request(
        "https://registry.npmjs.org/oh-my-embedded/latest",
        headers={"User-Agent": "Mozilla/5.0"}
    )
    npm_ver = json.loads(urllib.request.urlopen(req, timeout=15).read()).get("version", "?")
except Exception:
    pass

# --- Build report ---
lines = [
    f"# Power Electronics x AI Agent Daily Research",
    f"",
    f"**Date**: {today}",
    f"",
    f"---",
    f"",
    f"## New Papers",
    f"",
]
for p in papers:
    lines.append(f"- **{p['title']}**")
    lines.append(f"  - Authors: {p['authors']}")
    lines.append(f"  - URL: {p['url']}")
    lines.append("")
if not papers:
    lines.append("(No papers found today)")
    lines.append("")

lines += ["---", "", "## GitHub Projects", ""]
for r in repos:
    lines.append(f"- [{r['name']}]({r['url']}) ⭐{r['stars']} | updated {r['updated']}")
    if r['desc']:
        lines.append(f"  - {r['desc']}")
    lines.append("")
if not repos:
    lines.append("(No projects found)")
    lines.append("")

lines += ["---", "", "## Tool Versions", ""]
lines.append(f"| Tool | Version |")
lines.append(f"|------|---------|")
lines.append(f"| oh-my-embedded | {npm_ver} |")
lines.append(f"| Simulink Agentic Toolkit | [GitHub](https://github.com/matlab/simulink-agentic-toolkit) |")
lines.append(f"| kicad-mcp | [GitHub](https://github.com/blwfish/kicad-mcp) |")
lines.append("")

# --- LLM Summary (optional) ---
if api_key:
    try:
        paper_text = "\n".join(f"- {p['title']}" for p in papers[:5])
        repo_text = "\n".join(f"- {r['name']}: {r['desc'][:80]}" for r in repos[:5])
        prompt = f"Summarize today's power electronics AI research findings in Chinese:\n\n## Papers\n{paper_text or 'None'}\n\n## GitHub\n{repo_text or 'None'}\n\n## Tools\noh-my-embedded v{npm_ver}\n\nOutput as short paragraphs."

        # Try DeepSeek API (or OpenAI-compatible)
        payload = json.dumps({
            "model": "deepseek-chat",
            "messages": [
                {"role": "system", "content": "你是电力电子领域研究助理，用中文输出简洁摘要。"},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 1024,
            "temperature": 0.3
        }).encode()

        req = urllib.request.Request(
            "https://api.deepseek.com/chat/completions",
            data=payload,
            headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"},
            method="POST"
        )
        resp = urllib.request.urlopen(req, timeout=60)
        result = json.loads(resp.read())
        summary = result["choices"][0]["message"]["content"]
        lines += ["---", "", "## AI Summary", "", summary, ""]
    except Exception as e:
        lines += ["", f"<!-- LLM call failed: {e} -->", ""]

lines += ["---", "", "*Auto-generated by GitHub Actions*", ""]
report = "\n".join(lines)

# --- Write ---
path = os.path.join(REPORT_DIR, f"{today}.md")
with open(path, "w", encoding="utf-8") as f:
    f.write(report)
print(f"Report written: {path}")
